{% set name = "fslpy" %}
{% set version = "3.4.0" %}
{% set sha256 = "6de7f2d914c5fb2bf3c6a5426d8e2509d10b79b7d67349c882f9860ce34a7386" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - test_dicom.py.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - imcp           = fsl.scripts.imcp:main
    - imln           = fsl.scripts.imln:main
    - immv           = fsl.scripts.immv:main
    - imrm           = fsl.scripts.immv:main
    - imglob         = fsl.scripts.imglob:main
    - imtest         = fsl.scripts.imtest:main
    - remove_ext     = fsl.scripts.remove_ext:main
    - fsl_abspath    = fsl.scripts.fsl_abspath:main
    - Text2Vest      = fsl.scripts.Text2Vest:main
    - Vest2Text      = fsl.scripts.Vest2Text:main
    - atlasq         = fsl.scripts.atlasq:main
    - atlasquery     = fsl.scripts.atlasq:atlasquery_emulation
    - fsl_ents       = fsl.scripts.fsl_ents:main
    - resample_image = fsl.scripts.resample_image:main
    - fsl_apply_x5   = fsl.scripts.fsl_apply_x5:main
    - fsl_convert_x5 = fsl.scripts.fsl_convert_x5:main

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
  run:
    - python >=3.6
    - {{ pin_compatible('numpy') }}
    - scipy >=0.18
    - nibabel >=2.4
    - six >=1.*
    - h5py >=2.9
    - dataclasses
  run_constrained:
    - indexed_gzip >=0.7
    - wxpython >=4
    - trimesh >=2.37.29
    - rtree >=0.8.3.*
    - dcm2niix >=1.0.20171215
    - pillow >=3.2.0

test:
  source_files:
    - tests
  requires:
    - mock
    - coverage
    - pytest
    - pytest-cov
    - trimesh >=2.37.29
    - rtree >=0.8.3
    - indexed_gzip >=0.7
    - dcm2niix >=1.0.20171215
    - pillow >=3.2.0
  commands:
    - pytest -x -v --cov=fsl -m "not (wxtest or unixtest or longtest or fsltest or noroottest)" -k "not (fslsub or fslstats)" tests


about:
  home: https://git.fmrib.ox.ac.uk/fsl/fslpy/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The FSL Python library
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fslpy/

extra:
  recipe-maintainers:
    - pauldmccarthy
