{% set name = "fslpy" %}
{% set version = "2.6.0" %}
{% set sha256 = "5d788de54cc919d04d2a7e3af22a2aed823433e1bf94691c539450d255e2af33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - immv           = fsl.scripts.immv:main
    - imcp           = fsl.scripts.imcp:main
    - imglob         = fsl.scripts.imglob:main
    - atlasq         = fsl.scripts.atlasq:main
    - atlasquery     = fsl.scripts.atlasq:atlasquery_emulation
    - fsl_ents       = fsl.scripts.fsl_ents:main
    - resample_image = fsl.scripts.resample_image:main
    - fsl_apply_x5   = fsl.scripts.fsl_apply_x5:main
    - fsl_convert_x5 = fsl.scripts.fsl_convert_x5:main

requirements:
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.18
    - nibabel >=2.3.1
    - six 1.*
  run_constrained:
    - indexed_gzip >=0.7
    - wxpython >=4
    - trimesh >=2.37.29
    - rtree 0.8.3.*
    - dcm2niix 1.0.20181114
    - pillow >=3.2.0

test:
  source_files:
    - tests
  requires:
    - mock
    - coverage
    - pytest
    - pytest-cov
    - trimesh >=2.37.29
    - rtree 0.8.3.*
    - indexed_gzip >=0.7
    - dcm2niix 1.0.20181114
    - pillow >=3.2.0
  commands:
    - pytest -x -v --cov=fsl -m "not (wxtest or unixtest or longtest or fsltest or noroottest)" tests


about:
  home: https://git.fmrib.ox.ac.uk/fsl/fslpy/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The FSL Python library'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fslpy/

extra:
  recipe-maintainers:
    - pauldmccarthy
