{% set name = "fslpy" %}
{% set version = "1.13.3" %}
{% set sha256 = "5ce99418d2731eb1ff17c92550bf067b337730926c01f671030b7f04c87cbcc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - immv          = fsl.scripts.immv:main
    - imcp          = fsl.scripts.imcp:main
    - imglob        = fsl.scripts.imglob:main
    - atlasq        = fsl.scripts.atlasq:main
    - atlasquery    = fsl.scripts.atlasq:atlasquery_emulation
    - extract_noise = fsl.scripts.extract_noise:main
    - fsl_ents      = fsl.scripts.fsl_ents:main

requirements:
  build:
    - python
    - pip
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - deprecation >=1.*,<=2.*
    - {{ pin_compatible('numpy') }}
    - scipy >=0.18,<2
    - nibabel 2.*
    - six 1.*
  run_constrained:
    - indexed_gzip >=0.7,<1.*
    - wxpython <4.1
    - trimesh >=2.22.28,<3
    - rtree 0.8.3
    - dcm2niix 1.0.20180622

test:
  source_files:
    - tests
  requires:
    - mock 2.*
    - coverage 4.*
    - pytest 3.*
    - pytest-cov 2.*
    - trimesh >= 2.22.28,<3
    - rtree 0.8.3
    - indexed_gzip >=0.7,<1.*
    - dcm2niix 1.0.20180622
  commands:
    - pytest -x -v --cov=fsl -m "not (wxtest or unixtest or longtest or fsltest or noroottest)"


about:
  home: https://git.fmrib.ox.ac.uk/fsl/fslpy/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The FSL Python library'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fslpy/

extra:
  recipe-maintainers:
    - pauldmccarthy
