travis:
  secure:
    BINSTAR_TOKEN: Fbh6tfwb8KqDvHq3ZoAhSi0RMfjkWxJ5vplvKiNxFpi0Fdy70SryCkxq77EjD7HuLMQsboHKajVhQqSmSPAMe92I6iAwLY0JbJ9ocY2u46LJ+Hu6gq/NxFIrJJjffiOTSmw1EnyP+RvvlFazL+H9tZi9ztHhLM/YviRiLC0rvHIbcv6i3RVAslkdKXZuSoqEMoEF4dRSHgVIvALWS4SxE7lhJ04EcFPdCh3QurM6Bhbegvt/T/QSzkCkkpQk+/rbWlYhROJBFr03kjodxUwt0ON9yhgd5KO9MU1CcKslSpQ5idGMMP0VO2Ne32mj12Yj93ZdUynklL/tNrlVJBL9OHRCxkcDcGNGcVtPrjcMZuOH7MCKGa5JKCZjNNFznE4xIZepPHztAnkOvS1FFz5kTR0l3Rjd8yMOl/MieWilGOMpZAq3NA0K5lwlMtz3Iwb3A0CBVMzt6v+/JL/K7+a06WUcWIPR/ycMVbCJn40UTUGQgIkdeYz85W57EeIWFMDoxt/KBMjm7Fco8eqAVlRhHjRzhcDQS9Q2OH3RDkkxJh2Ig8CV9Ec9WydXyFX7sc0wPrPPjtX1MW4nyZurYr8laagY+2tP9bmLxyyj4SniIankYkWeovKLeuYDrdS0HH0WqgitsSbvvYqliq+P3kWVRFuGCCiOcH5YtLKUBo0RC7s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
